apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zerotier-ingress-helm.fullname" . }}-ztidentity
  labels:
    {{- include "zerotier-ingress-helm.labels" . | nindent 4 }}
type: Opaque
data:
  identity.public: {{ .Values.zerotier.identity.public | b64enc }}
  identity.secret: {{ .Values.zerotier.identity.secret | b64enc }}
