apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "crisp-status-local.fullname" . }}-config
  labels:
    {{- include "crisp-status-local.labels" . | nindent 4 }}
stringData:
  config.toml: |-
    [server]
    log_level = {{ .Values.logLevel | default "info" | quote }}
    [report]
    token = {{ .Values.crispReporterToken | quote}}
